### ISSUE TITLE
FormattedText should extend TextEnvelope

### ISSUE THREAD

**Issue by dgroup** [yegor256/cactoos#994] opened 2019-01-06 11:00 UTC
Now the `FormattedText` doesn't extend `TextEnvelope` thus such methods like `toString`, `hashCode`, `equals` have default implementation.

**Comment by 0crat** [comment] 2019-01-06 11:00
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment] 2019-01-10 01:40
@dgroup this is a duplicate of #929

**Closed by llorllale** 2019-01-10 01:40 UTC

**Comment by 0crat** [comment] 2019-01-10 02:02
Job `gh:yegor256/cactoos#994` is not assigned, can't get performer

**Comment by 0crat** [comment] 2019-01-10 02:02
This job is not in scope

**Comment by dgroup** [comment] 2019-01-10 19:31
@llorllale, please ignore my comment, I've checked the wrong issue.
