### ISSUE TITLE
Mutable collections

### ISSUE THREAD

**Issue by Iprogrammerr** [yegor256/cactoos#1008] opened 2019-01-15 06:53 UTC
We should create MutableCollectionEnvelope. Objects immutability is our core principle, but I think that mutability of collections is something different and it is often the case that we need them (#898).

**Comment by 0crat** [comment] 2019-01-15 06:53
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by wladyan** [comment] 2019-01-15 11:47
@Iprogrammerr I think envelopes must be orthogonal to immutability principle (#947).

**Comment by Iprogrammerr** [comment] 2019-01-15 20:23
@wladyan I agree. I propose to refactor CollectionEnvelope so that it does not care about immutability as described in #947. We then could add ImmutableCollection decorator that will work in the same manner as CollectionEnvelope is right now. I am willing to do that. @llorllale  WDYT?

**Comment by llorllale** [comment] 2019-01-16 01:53
@Iprogrammerr this is a duplicate of #947

**Closed by llorllale** 2019-01-16 01:53 UTC
