### ISSUE TITLE
LengthOfIterator asValue() must not be called twice

### ISSUE THREAD

**Issue by Timmeey** [yegor256/cactoos#85] opened 2017-06-05 18:27 UTC
LengthOfIterable.asValue() can only be called once.
Subsequent calls will just return 0.

Reproduce:
Create an Instance of LengthOfIterator
Call asValue() twice and compare both results to see the results are different

Expected:
Both results be the same.

Test Code:
```
@Test
public void immuatableLength() {
  LengthOfIterator length = new LengthOfIterator(
    new ArrayAsIterable<String>("muh", "kuh").iterator()
  );
  MatcherAssert.assertThat("Iterator length should not change because of a call to asValue",
                                 length.asValue() == length.asValue());
}

**Comment by 0crat** [comment] 2017-06-05 18:27
@timmeey I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment] 2017-06-07 05:59
@Timmeey I believe it's by design. The size of an iterator is "how much more elements can be pulled out of it". If there is nothing left to pull the size is zero. Or you don't think so?

**Comment by Timmeey** [comment] 2017-06-07 18:49
Yes that is correct. But the method will consume an iterator. So if i have my iterator, and want to know how much is left, it will tell me how much WAS left, but since it consumes the iterator it would not be of much use to me i think. At least i would not expect that i could still pull x elements from the iterator, if LengthOfIterator returns x, but it will be empty after that.

Either we should rename it, or try to "clone" the iterator.

not sure what the intention of this class is otherwise.

**Comment by yegor256** [comment] 2017-06-08 07:16
@Timmeey I get your point. Here is how I would use it: retrieve the list of items from the database, calculate the length and render this number in HTML. That's it. I'm not interested in the items, only in the amount of them.

I would suggest adding a detailed explanation of this problem to the Javadoc block of the class. WDYT?

**Comment by dusan-rychnovsky** [comment] 2017-06-08 07:57
Hi, @yegor256 if you only need to know the number of items in the database, I believe you should use a "SELECT Count(*)", istead of a "SELECT *" + counting the items in memory.

**Comment by Timmeey** [comment] 2017-06-08 12:16
@dusan-rychnovsky that is not the point. @yegor256 used a concret example to show the general type of usage. Recommending specific solutions for his example problem that have nothing to do with what he tried to showcase is not really helpful. But yes, you are right, if you just want to know how many of something are in the DB. But in this instance we would already have started showing a few elements, and now want to know how many would be left from the query.


@yegor256 Yes adding javadoc would help, but i'm not sure it is enough. It's just my feeling that a "getter" of length should have no side-effects, even if a javadoc states that. (by the way i just randomly found https://github.com/anupcowkur/here-be-dragons and seriously are considering to use it in my private small little things)
Maybe a new name for the class, that clearly states that this will have sideeffects would be better than just a long javadoc
Maybe something along the lines of `ConsumingLengthOfIterator` or `LengthOfConsumedIterator`?
WDYT?

But i will go ahead and draft up some Javadoc for this anyway

**Comment by dusan-rychnovsky** [comment] 2017-06-08 12:21
@Timmeey I wanted to point out that @yegor256 's example is absurd. IMO it is very important to use real examples when driving how a library should look like / behave. Not tailor the library to some hypothetical use cases.

**Comment by yegor256** [comment] 2017-06-12 12:27
@Timmeey check this out: https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/Iterators.html#size-java.util.Iterator-

**Comment by yegor256** [comment] 2017-06-21 06:52
@Timmeey see 	6a27707 This is what you need to do if you want to re-use the iterator:

```java
Scalar<Long> len = new LengthOfIterator(new StickyIterator(source));
len.asValue() == len.asValue();
```

**Comment by ashtonhogan** [comment] 2018-04-17 11:12
@Timmeey it looks like this has been solved, perhaps we can document the findings somewhere? Otherwise, can this be closed?

**Comment by llorllale** [comment] 2018-04-18 18:04
@Timmeey please close this issue

**Closed** 2018-04-20 16:44 UTC

**Comment by 0crat** [comment] 2018-04-20 16:59
The job is not in WBS, won't close the order
