### ISSUE TITLE
TextEnvelope equals is not symmetric 

### ISSUE THREAD

**Issue by g4s8** [yegor256/cactoos#1156] opened 2019-07-02 15:28 UTC
https://github.com/yegor256/cactoos/blob/100885a4638555d30fb56beefbb6691108b30d0f/src/main/java/org/cactoos/text/TextEnvelope.java#L79-L90

From Java `Object` [docs](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#equals(java.lang.Object)):
>  The equals method implements an equivalence relation on non-null object references:
>
>    It is reflexive: for any non-null reference value x, x.equals(x) should return true.
>    It is symmetric: for any non-null reference values x and y, x.equals(y) should return true if  and only if y.equals(x) returns true.
>    It is transitive: for any non-null reference values x, y, and z, if x.equals(y) returns true and y.equals(z) returns true, then x.equals(z) should return true.
>    It is consistent: for any non-null reference values x and y, multiple invocations of x.equals(y) consistently return true or consistently return false, provided no information used in equals comparisons on the objects is modified.
>    For any non-null reference value x, x.equals(null) should return false. 

But `TextEnvelope` `equals()` implementation is not symmetric:
```java
class Env extends TextEnvelope {
  public Env(String str) {
    super(new TextOf(str));
  }
}

class Txt implements Text {
  private final String str;
  public Txt(final String str) {
    this.str = str;
  }
  @Override
  public String asString() {
    return this.str;
  }
}

final String str = "test";
Text env = new Env(str)
Text txt = new Txt(str)
env.equals(txt) // returns true
txt.equals(env) // returns false
```

**Comment by 0crat** [comment] 2019-07-02 15:28
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-07-02 15:28
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment] 2019-07-02 23:29
@g4s8 you rolled your own implementation of `Text` with `Txt` in your example... that means you didn't extend `TextEnvelope`, and I see that you also didn't implement `equals()`. Hence this happens: `txt.equals(env) // returns false`

**Comment by g4s8** [comment] 2019-07-03 05:53
@llorllale that's true, but I think it's a valid case, since anybody can implement `Text` interface without `equals()` or with standard `equals()` implementation, e.g.
```java
class MyText implements Text {
   ...
  @Override
  public void equals(Object other) {
    if (!(other instanceof MyText)) {
      return false;
    }
   // other checks
  }
}
```

So I'd suggest adding type check in `TextEnvelope.equals`, it will make it symmetric, because `equals` method is marked as `final`, so all subclass `equals` calls will go to `TextEnvelope` implementation.

**Comment by llorllale** [comment] 2019-07-04 01:20
@g4s8 `TextEnvelope#equals` already has a type check on line 84. I don't understand where the issue is.

**Comment by g4s8** [comment] 2019-07-04 09:10
@llorllale but it checks that other object is a `Text`, I think it should check with `TextEnvelpe`:
```diff
             new And( 
-                () -> obj instanceof Text, 
+                () -> obj instanceof TextEnvelope,
                 () -> new UncheckedText(this)
```

**Comment by llorllale** [comment] 2019-07-04 18:38
@g4s8 oh, I think I see what you mean now.

My question is: would this change *really* be useful? Is it causing an actual bug somewhere? Or is this suggestion entirely motivated from a purist point of view?

**Comment by g4s8** [comment] 2019-07-04 19:30
@llorllale it's motivated from library user point of view: I may not check source code of `TextEnvelope` before using it, and I can easily implement `Text` somewhere with equals method, so I may get unpredictable bug which will depend on order of method calls, e.g. if I have text implementtion `SomeText` and `TextEnvelope` subclass `FormattedText`, I'd expect that code:
```java
new SomeText().equals(new FormattedText("..."))
```
will return same result as
```java
new FormattedText("...").equals(new SomeText())
```

**Comment by victornoel** [comment] 2019-07-14 09:55
@g4s8 @llorllale aren't you in the middle of a discussion trying to solve all that is bad with using inheritance? :)

Envelopes are not meant to implement behaviour but delegate to a wrapped object.

I personally think that `TextOf` or `Text.Default` could implement `equals`, `hashCode` and `toString` and take a `Scalar` so that all the implementation of `Text` that want to have the same behaviour simply delegate to it. In this case, `TextEnvelope` will be useful to simplify the task of delegating.

Or introduce an `AbstractText`, stop robbing envelopes of their meaning and completely accept that you are doing inheritance.

See https://github.com/llorllale/cactoos-matchers/issues/135 for a similar discussion.

**Comment by llorllale** [comment] 2019-07-20 18:32
@victornoel nope - @g4s8 is pointing to a deeper problem that would apply to your solution as well.

**Comment by victornoel** [comment] 2019-07-20 18:40
@llorllale I understand that, but I believe we would be better served by having a real `TextEnvelope` and then a `ScalarText` that can implements `equals` properly. I think also that if you do that, then the `equals` method of `ScalarText` just need to compare the value of `Text#asString()` with its own and the symmetry problem is solved if I'm not mistaken.

**Comment by llorllale** [comment] 2019-07-20 18:49
@g4s8 

> I can easily implement Text somewhere with equals method, so I may get unpredictable bug which will depend on order of method calls

Two `Text`s are equal solely if their string contents (defined as the output of `asString()`) are equal. If your custom `Text` does not honor this then it's not implementing the contract and it's violating LSP.

**Comment by g4s8** [comment] 2019-07-21 05:01
@llorllale but what if I have a `Text` with dynamic `asString` result? For instance text based on file:
```java
class FileContent implements Text {
  private Path file;
  
  @Override
  public String asString() {
    return new String(Files.readAllBytes(this.file));
  }
}
```
in that case I'd say that two instances are equal if they have the same state (`file`), but checking `asString` won't get real state of the instance, since file content may change, and `equals` may return false-positive results, So I'd implement `equals` like this:
```java
public boolean equals(Object obj) {
  return Objects.equals(this.file, FileContent.class.cast(obj).file);
}
```

**Comment by victornoel** [comment] 2019-07-21 08:27
> in that case I'd say that two instances are equal if they have the same state (file), but checking asString won't get real state of the instance, since file content may change, and equals may return false-positive results

@g4s8 raises a good point, and is highlighting another problem of envelopes we haven't tackled yet: when using envelopes for some of your implementations, you can't rely on reflection and casting.

Because if you have `MyFileText extends TextEnvelope` and delegates to `FileText`, I suppose you would expect that `new FileText(...).equals(new MyFileText(...))` would work if they delegate to the same file.

But they won't, because `FileText` doesn't know about `TextEnvelope` and will just conclude `MyFileText` is not of the right class.

I don't think there is a solution for that, or do you have something in mind (with current or my proposed design, cf https://github.com/llorllale/cactoos-matchers/issues/135#issuecomment-513497027, whatever) @g4s8 ?

**Comment by g4s8** [comment] 2019-07-21 09:12
@victornoel @llorllale if I really need to compare two texts by `asString` result, I'd create new class to do that:
```java
final class EqText implements Text {
  private final Text txt;

  @Override
  public String asString() {
    return this.txt.asString();
  }

  @Override
  public boolean equals(Object other) {
    return (other instanceof EqText) 
      && Objects.equals(this.asString(), EqText.class.cast(other).asString());
}
```

**Comment by fanifieiev** [comment] 2019-11-13 21:47
@g4s8 @paulodamaso @victornoel 
I think one of the solutions to make equality work properly is to introduce `canEqual` method as described here: http://marcus-christie.blogspot.com/2014/03/scala-object-equality-and-canequal.html
By the way, `lombok` uses the same approach and is used in [Takes ](https://github.com/yegor256/takes) framework

**Comment by victornoel** [comment] 2020-09-13 16:59
@g4s8 I'm going to close this, there is some discussion on that matter in #1241 but concerning `TextEnvelope.equals` (moved to `TextOf`, the envelope just being an envelope, so there is no more inherited behaviour from the envelope), I have this conclusion: https://github.com/yegor256/cactoos/pull/1458#discussion_r487550572

**Closed by victornoel** 2020-09-13 16:59 UTC

**Comment by 0crat** [comment] 2020-09-13 17:17
Job `gh:yegor256/cactoos#1156` is not assigned, can't get performer
