### ISSUE TITLE
Some classes that perform Input/Output (LengthOf, BytesOf, ...) close the stream

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1449] opened 2020-09-10 08:34 UTC
Some classes as `LengthOf` closes the `Input` after performed the operation. But often we need keep the `Input` stream opened even after it. So, let's create a decorator to `Input` and `Output` that allows keep these streams opened.

**Comment by victornoel** [comment] 2020-09-10 08:36
@fabriciofx or we could also just not close those `Input` or `Output` in any class and introduce some concept to wrap operations that manipulates `Input`/`Output` to close them at the end (a bit like try-with-resource).

I'm not sure what is best…

**Comment by fabriciofx** [comment] 2020-09-10 08:43
@victornoel I think not close after the manipulation better. As say the golden rule: *"Who allocated the resource is the responsible to deallocated it". A try-with-resourced kind of class is a good idea too. :)

**Comment by victornoel** [comment] 2020-09-13 14:30
@fabriciofx actually, after some thought, I'm not sure, because when you call `Input.stream()`, it means you could retrieve a new stream, so you HAVE to close it at the end.

Then, it means your first proposal was actually best indeed: i.e., it is the `Input` object creator that decides how the streams returned from `stream` will behave.

**Comment by victornoel** [comment] 2020-09-13 14:30
@0crat in

**Comment by victornoel** [comment] 2020-09-26 15:40
@fabriciofx some extra requirements for this job for the DEV that will take it: we must find all the classes that closes the stream like this, document them about this behaviour and refer to the existence of the new classes we should introduce that prevent stream closing

**Comment by baudoliver7** [comment] 2021-03-04 10:10
@victornoel Let's me find all the classes that close the stream like mentioned by @fabriciofx, document them properly and add a todo. Isn't it ?

**Comment by victornoel** [comment] 2021-03-04 10:16
@baudoliver7 you can do it either order you want yes: first document then todo for implementing the new decorators, or first implement the new decorators and then todo to document the classes.

**Comment by baudoliver7** [comment] 2021-03-04 10:38
@victornoel Ok. Let's us implement the new decorators :)

**Comment by baudoliver7** [comment] 2021-03-04 10:39
@victornoel What names could you suggest me ?

**Comment by victornoel** [comment] 2021-03-04 10:40
@baudoliver7 hehe, no idea actually, @fabriciofx would you have an idea?

Could you propose a name and we discuss it in the PR maybe?

**Comment by baudoliver7** [comment] 2021-03-04 10:43
@victornoel Yes, I will do it.

**Comment by andreoss** [comment] 2021-03-08 02:38
@fabriciofx 
Keeping `OutputStream` opened might be handy, but what is the point of doing so for `InputStream`?

First invocation of `new LenghtOf(new SafeInput(input))` will return correct length, the second will return 0 in your case, instead of throwing an exception (current behaviour). `SafeInput` should have some mark/reset logic at `close` for the original stream in order to avoid that.

Also `LengthOf` sometimes is explicitly used as a terminal operation on streams (with `TeeInput` for example), so if `LengthOf` won't close its streams existing code will break

**Comment by baudoliver7** [comment] 2021-03-08 12:16
@andreoss
We fixed it (First invocation of `new LenghtOf(new SafeInput(input))` will return correct length, the second will return 0 in your case) in the last commit. Thanks.

**Comment by baudoliver7** [comment] 2021-03-08 12:37
@andreoss Also, if someone want `LengthOf` to close original streams, he should not have to decorate original `Input` with `SafeInput`. But in this case, the class that allocated the resource is responsible to deallocated it.

**Comment by victornoel** [comment] 2021-03-08 14:33
@andreoss @baudoliver7 it is normal that using `LengthOf` twice on a `SafeInput` will have the second time return 0, we don't want to prevent this. And actually, you don't know what the underlying stream is made of: maybe you read it once, then later on, there is again some data in it. That's why you need something like SafeInput, to prevent the stream consumer to close it when, as the user (or maybe creator) of that stream, you do know its behaviour is a bit more tricky than that.

This also applies to ouput: when I am producing a Zip with ZipOutputStream, I dont want to close the stream inbetween writing each file for example.

The whole point is to give more power to the code that composes the various objects together, because that code may know better than the code consuming the stream.

**Comment by 0pdd** [comment] 2021-03-22 09:38
@fabriciofx the puzzle [#1577](https://github.com/yegor256/cactoos/issues/1577) is still not solved.

**Comment by victornoel** [comment] 2021-03-22 09:44
@fabriciofx sorry, this was automatically closed because the "closed" keywork was in the commit message ^^ I hope the solution is good for you, if not please reopen a ticket :)

**Comment by 0crat** [comment] 2021-03-22 15:32
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) (its creator); I won't close the order; please, re-open it and ask @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) to close it

**Closed** 2021-03-22 15:48 UTC
Labels: 0crat/role/DEV, 0crat/scope

**Comment by victornoel** [comment] 2021-03-22 18:18
@0crat out

**Comment by 0crat** [comment] 2021-03-22 19:52
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2021-03-22 19:53
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/1449#issuecomment-804287352))

@victornoel Job `gh:yegor256/cactoos#1449` is not assigned, can't get performer

**Comment by sereshqua** [comment] 2021-03-22 19:58
@0crat quality good

**Comment by baudoliver7** [comment] 2021-04-07 00:19
@0crat status

**Comment by 0crat** [comment] 2021-04-07 01:23
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1449#issuecomment-814514116))

@baudoliver7 This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1449](https://github.com/yegor256/cactoos/issues/1449) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231449%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0pdd** [comment] 2022-07-11 03:30
@fabriciofx the puzzle [#unknown]() is still not solved.
