### ISSUE TITLE
Wrong count files in Directory

### ISSUE THREAD

**Issue by alex-semenyuk** [yegor256/cactoos#599] opened 2018-02-03 20:44 UTC
org.cactoos.io.DirectoryTest:

```
   @Test
    public void listsFilesInDirectory() throws IOException {
        final Path dir = Files.createTempDirectory("x1");
        dir.resolve("x/y").toFile().mkdirs();
        Files.write(dir.resolve("x/y/test"), "".getBytes());
        MatcherAssert.assertThat(
            "Can't list files in a directory",
            new Directory(dir),
            // @checkstyle MagicNumber (1 line)
            Matchers.iterableWithSize(4)
        );
    }

```

Actually in this test only one file is created, not 4. `Files.walk` from org.cactoos.io.Directory#iterator includes sub directories in this count.

**Comment by 0crat** [comment] 2018-02-03 20:45
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment] 2018-02-05 14:18
@alex-semenyuk this is by design, I believe. The `Directory` class is multi-purpose and must work in situations where users are interested in files _and_ directories. Or I'm wrong?

**Comment by alex-semenyuk** [comment] 2018-02-05 14:24
@yegor256 then a test name `listsFilesInDirectory` and javadoc to class `Files in a directory` are confused

**Comment by yegor256** [comment] 2018-02-05 14:26
@alex-semenyuk I agree, we need better explanation in the documentation.

**Comment by 0crat** [comment] 2018-02-05 14:26
Job [#599](https://github.com/yegor256/cactoos/issues/599) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-02-08 21:17
The job [#599](https://github.com/yegor256/cactoos/issues/599) assigned to @sharpler[/z](https://www.0crat.com/u/sharpler). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment] 2018-02-13 21:24
@sharpler[/z](https://www.0crat.com/u/sharpler) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment] 2018-02-16 21:18
@sharpler[/z](https://www.0crat.com/u/sharpler) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by SharplEr** [comment] 2018-02-17 17:28
@alex-semenyuk  PR was merged https://github.com/yegor256/cactoos/pull/628

**Comment by SharplEr** [comment] 2018-02-18 12:26
@0crat waiting

**Comment by 0crat** [comment] 2018-02-18 12:26
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/599#issuecomment-366512435))

@SharplEr The impediment for [#599](https://github.com/yegor256/cactoos/issues/599) was registered successfully by @sharpler[/z](https://www.0crat.com/u/sharpler)

**Comment by SharplEr** [comment] 2018-02-18 12:28
@alex-semenyuk please close the issue)

**Comment by 0crat** [comment] 2018-02-18 17:42
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Closed** 2018-02-18 17:41 UTC
Labels: bug, scope

**Comment by ypshenychka** [comment] 2018-02-19 20:36
@0crat Quality good

**Comment by 0crat** [comment] 2018-02-19 20:43
> @0crat Quality good ([here](https://github.com/yegor256/cactoos/issues/599#issuecomment-366797194))

@ypshenychka Job `gh:yegor256/cactoos#599` is not assigned, can't get start time

**Comment by 0crat** [comment] 2018-02-19 20:44
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+165](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment] 2018-02-19 20:44
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+165](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment] 2018-02-19 20:44
Order was finished, quality was "good": +35 points just awarded to @sharpler[/z](https://www.0crat.com/u/sharpler), total is [+110](https://www.0crat.com/u/sharpler)
