### ISSUE TITLE
WriterAsOutputStream does not close the enclosed Writer

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#561] opened 2018-01-17 19:52 UTC
`WriterAsOutputStream` does not override `close()`, hence leaving the enclosed writer open. 

Example writing contents to a file and then deleting the file:
```java
        final Path temp = Files.createTempFile("", "");
        new TextOf(
            new TeeInput(
                new ResourceOf("org/cactoos/large-text.txt"),
                new OutputTo(
                    new WriterAsOutputStream(
                        new OutputStreamWriter(
                            new FileOutputStream(temp.toFile()),
                            StandardCharsets.UTF_8
                        ),
                        StandardCharsets.UTF_8,
                        345
                    )
                )
            )
        ).asString();
        Files.delete(temp);    //IOException "the file is being used by another process"
```

**Comment by 0crat** [comment] 2018-01-17 19:53
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-01-17 21:37
Job [#561](https://github.com/yegor256/cactoos/issues/561) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-01-17 21:39
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @llorllale[/z](http://www.0crat.com/u/llorllale), total is [+120](http://www.0crat.com/u/llorllale)

**Comment by amihaiemil** [comment] 2018-01-27 06:59
@yegor256 can I have this task?

**Comment by 0crat** [comment] 2018-01-31 04:35
The job [#561](https://github.com/yegor256/cactoos/issues/561) assigned to @rexim[/z](https://www.0crat.com/u/rexim). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by rexim** [comment] 2018-01-31 18:43
@llorllale cannot reproduce on my Linux system. Is it reproducible on Windows? You reported a similar problem reproducible in Windows environment #563

**Comment by llorllale** [comment] 2018-01-31 19:01
@rexim yes, it is consistently reproducible on Windows.

**Comment by 0crat** [comment] 2018-02-05 04:53
@rexim[/z](https://www.0crat.com/u/rexim) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by rexim** [comment] 2018-02-06 20:29
@0crat waiting

**Comment by 0crat** [comment] 2018-02-06 20:29
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/561#issuecomment-363555072))

@rexim The impediment for [#561](https://github.com/yegor256/cactoos/issues/561) was registered successfully by @rexim[/z](https://www.0crat.com/u/rexim)

**Closed** 2018-02-09 11:44 UTC
Labels: bug

**Comment by 0crat** [comment] 2018-02-09 11:47
Order was successfully finished: +30 points just awarded to @rexim[/z](https://www.0crat.com/u/rexim), total is [+105](https://www.0crat.com/u/rexim)

**Comment by 0crat** [comment] 2018-02-09 11:55
The job [#561](https://github.com/yegor256/cactoos/issues/561) is now out of scope

**Comment by llorllale** [comment] 2018-02-09 14:49
@yegor256 I believe I (the reporter of this ticket) should've been asked to close this

**Comment by yegor256** [comment] 2018-02-09 15:05
@llorllale yes, GitHub closes tickets automatically if a PR contains "closes" text somewhere. It's very annoying and I don't know how to stop them doing that.

**Comment by rexim** [comment] 2018-02-09 15:07
@yegor256 how about don't accept PR if it contains "close" and ask to remove it?
