### ISSUE TITLE
Most of ctors of InputStreamOf are not covered by unit tests

### ISSUE THREAD

**Issue by nick318** [yegor256/cactoos#675] opened 2018-02-17 15:36 UTC
Most of ctors of `InputStreamOf.java` are not covered by unit tests:
```
public InputStreamOf(final File file) {
        this(new InputOf(file));
    }
public InputStreamOf(final URL url) {
        this(new InputOf(url));
    }
public InputStreamOf(final URI uri) {
        this(new InputOf(uri));
    }
public InputStreamOf(final Bytes bytes) {
        this(new InputOf(bytes));
    }
public InputStreamOf(final byte[] bytes) {
        this(new InputOf(bytes));
    }
public InputStreamOf(final Text text) {
        this(text, StandardCharsets.UTF_8);
    }
public InputStreamOf(final Text text, final CharSequence charset) {
        this(new InputOf(text, charset));
    }
public InputStreamOf(final CharSequence text, final Charset charset) {
        this(new InputOf(text, charset));
    }
public InputStreamOf(final CharSequence text, final CharSequence charset) {
        this(new InputOf(text, charset));
    }
public InputStreamOf(final Reader rdr, final CharSequence charset) {
        this(new InputOf(rdr, charset));
    }
public InputStreamOf(final Reader rdr, final Charset cset, final int max) {
        this(new InputOf(rdr, cset, max));
    }
public InputStreamOf(final Reader rdr, final CharSequence charset,
        final int max) {
        this(new InputOf(rdr, charset, max));
    }
```
Expected:
All ctors of `InputStreamOf.java` are covered by unit tests

**Comment by 0crat** [comment] 2018-02-17 15:36
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-02-19 11:42
Job [#675](https://github.com/yegor256/cactoos/issues/675) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-02-19 11:46
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318), total is [+215](https://www.0crat.com/u/nick318)

**Comment by driver733** [comment] 2018-02-19 20:24
@nick318 @yegor256 duplicate of #661

**Comment by 0crat** [comment] 2018-03-01 09:03
The job [#675](https://github.com/yegor256/cactoos/issues/675) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), here is [why](https://www.0crat.com/footprint/C63314D6Z/600905975). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment] 2018-03-01 15:32
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Closed** 2018-03-01 15:31 UTC
Labels: bug, scope

**Comment by ypshenychka** [comment] 2018-03-01 15:48
@0crat quality bad

**Comment by 0crat** [comment] 2018-03-01 15:50
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment] 2018-03-01 15:51
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment] 2018-03-01 15:51
> @0crat quality bad ([here](https://github.com/yegor256/cactoos/issues/675#issuecomment-369634649))

@ypshenychka The job [#675](https://github.com/yegor256/cactoos/issues/675) is now out of scope
