### ISSUE TITLE
lengthOf.intValue() returns 0 when called the second time

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/cactoos#633] opened 2018-02-11 02:15 UTC
```
final LengthOf lengthOf = new LengthOf(new IterableOf<>(iterator));
System.out.println("leng " + lengthOf.intValue()); //Returns 26 for example
System.out.println("leng2 " + lengthOf.intValue()); //Returns 0
```

**Comment by 0crat** [comment] 2018-02-11 02:15
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by Maratori** [comment] 2018-02-11 18:24
This is a due to #625

**Comment by yegor256** [comment] 2018-02-12 14:10
@ashtonhogan duplicate of #625

**Comment by 0crat** [comment] 2018-02-12 14:10
Job `gh:yegor256/cactoos#633` is not assigned, can't get start time

**Closed by yegor256** 2018-02-12 14:10 UTC

**Comment by 0crat** [comment] 2018-02-12 14:20
Job [#633](https://github.com/yegor256/cactoos/issues/633) was not in scope
