### ISSUE TITLE
Equality

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#308] opened 2017-07-11 15:46 UTC
Let's implement `Comparison` like can see [here](http://www.yegor256.com/2017/07/11/how-to-redesign-equals.html). I'll handle it.

**Comment by yegor256** [comment] 2017-07-11 18:19
@fabriciofx right, let's do it.

**Comment by yegor256** [comment] 2017-07-11 18:20
@fabriciofx but let's call it `Equality`

**Comment by fabriciofx** [comment] 2017-07-11 18:24
@yegor256 Ok!

**Comment by fabriciofx** [comment] 2017-07-11 19:10
@yegor256 Could you review the PR? Thanks!

**Comment by fabriciofx** [comment] 2017-07-28 01:52
@svendiedrichsen Well, I don't know if it's better. The idea is give to developer the choice of use `NonNulls` or not. If I put `NonNull` inside `Equality`, we remove the power of choice. @yegor256 WDYT?

**Comment by svendiedrichsen** [comment] 2017-07-28 16:06
@fabriciofx: I'd say that the Equality object has to be in power to make this decision. But anyway the only difference that using NonNull brings is a better Exception suing a proper message. So imho Equality should be in charge of deciding to throw better exceptions.

But in general can't i see the use of NonNull in the first place. Doesn't it violate the first principle as stated for this project? Or shouldn't all objects of this project use such a NonNull implementation? WDYT?

**Comment by fabriciofx** [comment] 2018-01-10 05:52
@svendiedrichsen I don't think `Equality` should use a `NonNull` implementation. I think it must be simpler possible. @yegor256 WDYT? Should I continue with this issue? Should I close it?

**Comment by fabriciofx** [comment] 2018-01-26 05:56
@yegor256 ping!

**Comment by yegor256** [comment] 2018-01-29 17:28
@fabriciofx I don't see a link between NonNull and Equality. Anyway, it's necessary to see the code.

**Comment by llorllale** [comment] 2018-04-18 19:04
@0crat in

**Comment by llorllale** [comment] 2018-04-18 19:04
@0crat assign @fabriciofx

**Comment by 0crat** [comment] 2018-04-18 19:05
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/308#issuecomment-382495389))

@llorllale Job [#308](https://github.com/yegor256/cactoos/issues/308) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-04-18 19:06
> @0crat assign @fabriciofx  ([here](https://github.com/yegor256/cactoos/issues/308#issuecomment-382495414))

@llorllale The job [#308](https://github.com/yegor256/cactoos/issues/308) assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/1081915799); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment] 2018-04-18 19:06
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment] 2018-04-18 19:07
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment] 2018-04-18 19:07
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment] 2018-04-23 22:36
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment] 2018-05-02 21:20
The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#308](https://github.com/yegor256/cactoos/issues/308), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment] 2018-05-02 21:20
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment] 2018-05-02 21:50
The job [#308](https://github.com/yegor256/cactoos/issues/308) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1222152391); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by Vatavuk** [comment] 2018-05-05 17:58
@llorllale Please close this issue since @fabriciofx is inactive. It was solved in #809

**Comment by llorllale** [comment] 2018-05-05 20:25
@Vatavuk I agree, thanks.

**Closed by llorllale** 2018-05-05 20:25 UTC
Labels: scope

**Comment by 0crat** [comment] 2018-05-05 20:40
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2018-05-05 20:40
The job [#308](https://github.com/yegor256/cactoos/issues/308) is now out of scope

**Comment by elenavolokhova** [comment] 2018-05-06 16:05
@svendiedrichsen According to our Policy:
> Messages in a job always start with a name of a user they are addressed to;

This comment was not addressed:
> How about using Bytes.NonNulls when assigning left/right in the Equality constructor? Thus you get some better exceptions. If so you should have some tests using NULL Bytes.

Please, confirm that you'll follow this rule in future.

**Comment by svendiedrichsen** [comment] 2018-05-06 17:42
@elenavolokhova Confirmed.

**Comment by elenavolokhova** [comment] 2018-05-06 19:17
@0crat quality acceptable
