### ISSUE TITLE
IterableOf from Iterator doesn't work

### ISSUE THREAD

**Issue by Maratori** [yegor256/cactoos#625] opened 2018-02-10 17:17 UTC
The instance of `IterableOf` created with `ctor(final Iterator<X> list)` doesn't behave as real `Iterable`.
It can be iterated only once by obvious reason.

**Comment by 0crat** [comment] 2018-02-10 17:17
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-02-12 13:36
Job [#625](https://github.com/yegor256/cactoos/issues/625) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-02-15 19:43
The job [#625](https://github.com/yegor256/cactoos/issues/625) assigned to @nick318[/z](https://www.0crat.com/u/nick318), here is [why](https://www.0crat.com/footprint/C63314D6Z/461943894). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by nick318** [comment] 2018-02-16 09:15
@0crat waiting

**Comment by 0crat** [comment] 2018-02-16 09:16
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/625#issuecomment-366181872))

@nick318 The impediment for [#625](https://github.com/yegor256/cactoos/issues/625) was registered successfully by @nick318[/z](https://www.0crat.com/u/nick318)

**Comment by nick318** [comment] 2018-02-16 10:03
@Maratori what is an expected behavior? Iterator can be iterated only once by java design.

**Comment by Maratori** [comment] 2018-02-16 10:15
@nick318 I believe there is no expected behavior. You can not copy any `Iterator`. For example you can not copy `org.cactoos.iterator.Cycled`.
I think that this ctor must be removed.

**Comment by nick318** [comment] 2018-02-16 10:18
@yegor256 Please, leave your decision about removing `ctor(final Iterator<X> list)`

**Comment by SharplEr** [comment] 2018-02-16 21:41
In my task, I found the same bug: https://github.com/yegor256/cactoos/issues/659

**Comment by nick318** [comment] 2018-02-17 15:10
@yegor256 take a look please

**Comment by nick318** [comment] 2018-02-18 08:55
@yegor256 take a look please

**Comment by yegor256** [comment] 2018-02-19 11:03
@nick318 @Maratori I think we should make sure `InterableOf` creates a proper `Iterable`, even when an `Iterator` is provided.

**Comment by nick318** [comment] 2018-02-19 11:13
@yegor256 What do you mean about making sure?

**Comment by yegor256** [comment] 2018-02-19 18:41
@Maratori @nick318 I think we can close this ticket, because of this decision: https://github.com/yegor256/cactoos/issues/677

**Comment by nick318** [comment] 2018-02-19 18:42
@yegor256 agree

**Closed** 2018-02-20 16:19 UTC
Labels: bug, scope

**Comment by 0crat** [comment] 2018-02-20 16:21
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment] 2018-02-20 16:26
@nick318 Just to make sure I understood thread correctly - no work was eventually finished around this issue, right?

**Comment by nick318** [comment] 2018-02-20 16:29
@ypshenychka yes, the issue does not make sense anymore.

**Comment by ypshenychka** [comment] 2018-02-20 16:30
@nick318 got it. Thanks.

**Comment by ypshenychka** [comment] 2018-02-20 16:30
@0crat quality bad

**Comment by 0crat** [comment] 2018-02-20 16:33
Quality is low, no payment, see [§31](http://datum.zerocracy.com/pages/policy.html#31)
