### ISSUE TITLE
why Filtered and not predictable, why a for each, and not streams?

### ISSUE THREAD

**Issue by pgermosen** [yegor256/cactoos#1] opened 2017-05-23 20:05 UTC

**Comment by yegor256** [comment] 2017-05-23 20:54
@pgermosen I don't think Streams is a good idea in OOP, in general

**Comment by yegor256** [comment] 2017-05-23 20:54
@pgermosen as for "predictable" -- I didn't understand. Can you give an example?

**Comment by pgermosen** [comment] 2017-05-23 22:23
Of course, streams are not oop , but is easy of use.

this example ?

> 
> new ForEach(
>   new ArrayAsIterable("how", "are", "you"),
>   i -> System.out.printf("Item: %s\n", i)
> )
 jdk 9 forEach in a collection
I understand better this, than the oop approached
List.of("how","are","you").forEach(i-> System.out.printf("Item: %s\n", i) )

**Comment by englishman** [comment] 2017-05-23 23:38
@pgermosen from my experience streams and other [message driving architectures](http://www.enterpriseintegrationpatterns.com) motivate split data and methods of it processing.

**Comment by pgermosen** [comment] 2017-05-24 01:23
Yes that is a motive of use.

But what i want to make a point is the following points for a new api to take in account 

- is easy of use
- readability


the example of To sort a list of words in the file

List<String> sorted = new SortedList<>(
  new IterableAsList(
    new TextAsLines(
      new InputAsString(
        new FileAsInput(
          new File("/tmp/names.txt")
        )
      )
    )
  )
);`

for me has the same readability than
if (x==true){
if (n==false){
}
if (y==x){
}else{
if (h==s){
}
}
}

**Comment by englishman** [comment] 2017-05-24 02:11
@pgermosen I'm not sure traditional declarative code will be more clear and shorter for this specific task. Moreover, I'm not sure `IterableAsList` in needed here at all.

**Comment by pgermosen** [comment] 2017-05-24 02:18
I think api that can be read like this, is clearer(not necessary shorted, sometimes extra text for clarity is a better) 

```
    new FileAsInput(
               new File("/tmp/names.txt")
        ).toInputAsString().toTextAsLine().toSortedList();
```

**Comment by yegor256** [comment] 2017-05-24 16:40
@pgermosen this "fluent" interface (`.toText().readLines().toSortedList()`) is very imperative. We want to stay declarative. That's why we need new objects instead of method chaining.

**Comment by englishman** [comment] 2017-05-24 17:14
@yegor256 it's quite declarative. The problem is different: it's always hard to support these fluent things combining smth new from individual objects and using inheritance.

**Comment by pgermosen** [comment] 2017-05-24 18:08
What is more important
 **clear and easy code** for the using developers using the library/framework
  or 
 to be hard to support the fluent api.

**Comment by yegor256** [comment] 2017-05-25 17:17
@pgermosen fluent interface is easy to use only because it's your habit to use it. Also, if you want it, there are plenty of libraries that do exactly the same as Cactoos, but in a traditional way.

**Comment by fabriciofx** [comment] 2017-06-23 23:28
@pgermosen Do you agree with this solution? If yes, could you close this issue? If not, could you explain why not? Thanks for your attention!

**Comment by andriyshevchenko** [comment] 2017-07-09 21:40
Don't you like the regular foreach yet present in java language? No lambdas needed. Dont make things too complex.

**Comment by ashtonhogan** [comment] 2017-07-23 10:30
How would you get around `InputStream`? Scenarios where a `Socket` is open and waiting for more data to come in and go out? What's the clean, OOP approach to this problem?

**Comment by llorllale** [comment] 2018-04-18 15:59
@pgermosen can we close this issue? Our [README](https://github.com/yegor256/cactoos/blob/master/README.md) states the motivations and design principles behind `cactoos`, and your request is unfortunately incompatible with them.

**Comment by llorllale** [comment] 2018-04-23 15:52
@pgermosen closing due to inactivity

**Closed by llorllale** 2018-04-23 15:52 UTC
Labels: question

**Comment by 0crat** [comment] 2018-04-23 16:08
The job is not in WBS, won't close the order
