### ISSUE TITLE
Immutable list is not really immutable 

### ISSUE THREAD

**Issue by quantumlexa** [yegor256/cactoos#1224] opened 2019-11-03 15:43 UTC
Please see the test:

```
    @Test
    public void testImmutability() {
        Immutable<String> immutable = new Immutable<>(new ArrayList<>(Arrays.asList("a", "b", "c")));
        int originalSize = immutable.size();
        immutable.subList(0, 2).add("d");
        Assert.assertEquals(originalSize, immutable.size());
    }

    @Test
    public void testImmutability2() {
        ArrayList<String> strings = new ArrayList<>(Arrays.asList("a", "b", "c"));
        Immutable<String> immutable = new Immutable<>(strings);
        int originalSize = immutable.size();
        strings.add("d");
        Assert.assertEquals(originalSize, immutable.size());
    }



```

**Comment by 0crat** [comment] 2019-11-03 15:43
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-11-03 15:43
@quantumlexa[/z](https://www.0crat.com/u/quantumlexa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by paulodamaso** [comment] 2019-11-06 03:07
@quantumlexa What behavior do you expect from this test execution?

**Comment by quantumlexa** [comment] 2019-11-06 03:13
> @quantumlexa What behavior do you expect from this test execution?

I'd expect from Immutable list to be immutable, i.e. once the object is created - there is no way to modify it.
Please see the following: https://docs.oracle.com/javase/tutorial/essential/concurrency/immutable.html

**Comment by paulodamaso** [comment] 2019-11-06 03:42
@0crat in

**Comment by 0crat** [comment] 2019-11-06 04:29
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1224#issuecomment-550129263))

@paulodamaso Job [#1224](https://github.com/yegor256/cactoos/issues/1224) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2019-11-06 04:37
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1224#issuecomment-550129263))

@paulodamaso Thanks for your contribution, @quantumlexa[/z](https://www.0crat.com/u/quantumlexa)! If you would be a member of [the project](https://www.0crat.com/p/C63314D6Z), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment] 2019-11-06 05:21
The job [#1224](https://github.com/yegor256/cactoos/issues/1224) assigned to @iakunin[/z](https://www.0crat.com/u/iakunin), here is [why](https://www.0crat.com/footprint/C63314D6Z/aeb45e97-1d88-4cda-a27c-dfcd7b59b6e4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fanifieiev** [comment] 2019-11-06 14:53
> > @quantumlexa What behavior do you expect from this test execution?
> 
> I'd expect from Immutable list to be immutable, i.e. once the object is created - there is no way to modify it.
> Please see the following: https://docs.oracle.com/javase/tutorial/essential/concurrency/immutable.html

@paulodamaso, @quantumlexa, @iakunin 
I would also like to mention, that the `subList` method should return immutable list as well.
For now it does not.

**Comment by fanifieiev** [comment] 2019-11-06 16:51
> @fanifieiev Yes, that is the cause of the problem

@paulodamaso The cause is not only because of `subList`, but in general as well.
As the second test shows above, it is achievable without `subList` as well.

**Comment by iakunin** [comment] 2019-11-09 11:57
@0crat wait for https://github.com/yegor256/cactoos/pull/1232 to be merged

**Comment by 0crat** [comment] 2019-11-09 11:59
> @0crat wait for https://github.com/yegor256/cactoos/pull/1232 to be merged ([here](https://github.com/yegor256/cactoos/issues/1224#issuecomment-552093194))

@iakunin The impediment for [#1224](https://github.com/yegor256/cactoos/issues/1224) was registered successfully by @iakunin[/z](https://www.0crat.com/u/iakunin)

**Comment by 0pdd** [comment] 2019-11-12 20:39
@quantumlexa the puzzle [#1236](https://github.com/yegor256/cactoos/issues/1236) is still not solved.

**Comment by iakunin** [comment] 2019-11-13 07:13
@quantumlexa @paulodamaso is this issue solved? Can we close it?

**Comment by iakunin** [comment] 2019-11-15 21:52
@quantumlexa @paulodamaso is this issue solved? Can we close it?

**Comment by fanifieiev** [comment] 2019-11-16 02:49
> @quantumlexa @paulodamaso is this issue solved? Can we close it?

@iakunin I think only @paulodamaso can answer this question and decide to close the issue, but he is not responding for the last couple of days.

**Comment by iakunin** [comment] 2019-11-16 08:36
@quantumlexa ping

**Comment by iakunin** [comment] 2019-11-16 08:41
> @iakunin I think only @paulodamaso can answer this question and decide to close the issue, but he is not responding for the last couple of days.

@fanifieiev yes, I asked @paulodamaso in Telegram and he advised me to ping @quantumlexa couple of times. And if it's no reply, then @paulodamaso will close this ticket. 

@quantumlexa ping.

**Comment by paulodamaso** [comment] 2019-11-18 13:52
@iakunin Thanks!

**Closed by paulodamaso** 2019-11-18 13:52 UTC
Labels: scope, waiting

**Comment by 0crat** [comment] 2019-11-18 14:11
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @iakunin[/z](https://www.0crat.com/u/iakunin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2019-11-18 14:11
The job [#1224](https://github.com/yegor256/cactoos/issues/1224) is now out of scope

**Comment by sereshqua** [comment] 2019-11-18 14:20
@quantumlexa please make sure that you start all your comments with the name of the user they are referred to, [see](https://github.com/yegor256/cactoos/issues/1224#issuecomment-550122995)

**Comment by iakunin** [comment] 2019-11-19 15:42
@sereshqua how long should we wait for @quantumlexa response to get this issue reviewed?

**Comment by sereshqua** [comment] 2019-11-19 15:53
@iakunin up to 5 days

**Comment by quantumlexa** [comment] 2019-11-19 16:50
@sereshqua  @iakunin I'm sorry guys, didn't know that you are waiting for me. As I'm not an owner the project, I just pointed out to the problem I found looking to the code - I'm good with either way.

**Comment by sereshqua** [comment] 2019-11-19 20:17
@quantumlexa the only thing you missed was to start your comment with the name of the user to whom you addressed it :)

**Comment by sereshqua** [comment] 2019-11-19 20:17
@0crat quality acceptable

**Comment by iakunin** [comment] 2019-11-20 11:22
@0crat status

**Comment by sereshqua** [comment] 2019-11-20 11:26
@iakunin seems like 0crat went down :) and did not process this issue yet

**Comment by sereshqua** [comment] 2019-11-20 11:26
@0crat quality acceptable

**Comment by iakunin** [comment] 2019-11-20 11:37
@sereshqua that's true. I hope he will awake soon :)

**Comment by 0crat** [comment] 2019-11-20 14:41
> @0crat quality acceptable  ([here](https://github.com/yegor256/cactoos/issues/1224#issuecomment-555962404))

@sereshqua There is no quality review for [#1224](https://github.com/yegor256/cactoos/issues/1224), no performer

**Comment by iakunin** [comment] 2019-11-20 14:48
@0crat status

**Comment by 0crat** [comment] 2019-11-20 14:51
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment] 2019-11-20 14:53
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1224#issuecomment-555961192))

@iakunin This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1224](https://github.com/yegor256/cactoos/issues/1224) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231224%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment] 2019-11-20 15:00
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1224#issuecomment-556035489))

@iakunin This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1224](https://github.com/yegor256/cactoos/issues/1224) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231224%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment] 2019-11-20 15:07
Order was finished, quality is "acceptable": +30 point(s) just awarded to @iakunin[/z](https://www.0crat.com/u/iakunin)

**Comment by 0pdd** [comment] 2020-02-03 19:23
@quantumlexa the only puzzle [#1236](https://github.com/yegor256/cactoos/issues/1236) is solved here.
