### ISSUE TITLE
TeeInput might leak

### ISSUE THREAD

**Issue by Serranya** [yegor256/cactoos#1024] opened 2019-01-18 20:37 UTC
Consider the following Code from the examples section of the README:

```java
new LengthOf(
  new TeeInput(
    "Hello, world!",
    new File("/code/a.txt")
  )
).intValue();
```

Because of https://github.com/yegor256/cactoos/pull/820 the `OutputStream` obtained from `File` will not be closed. It's also impossible for us to close the stream manually because the reference is lost. We just leave the resource open for the rest of the application.

I hit the problem in https://github.com/yegor256/takes/pull/942
```java
try (TempFile file = new TempFile()) {
  final Bytes body = new Utf8String("URL returnsCorrectLength!");
  new LengthOf(new TeeInput(body, file.value())).intValue();
  MatcherAssert.assertThat(
    "Body content of Body.Url doesn't have the correct length",
    new LengthOf(
      new Body.Url(file.value().toUri().toURL())
      ).intValue(),
      new IsEqual<>(body.asBytes().length)
    );
  }
}
```

The code runs fine on linux but fails on windows with:
```
java.nio.file.FileSystemException: 
C:\Users\appveyor\AppData\Local\Temp\1\4539165525569174340: The process cannot access the file because it is being used by another process.
```

We should at least fix the leaking example in the README and also add some warnings to the documentation of TeeInput.

**Comment by 0crat** [comment] 2019-01-18 20:37
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-01-18 20:37
@serranya[/z](https://www.0crat.com/u/serranya) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment] 2019-01-19 00:49
@Serranya 

I hadn't realized that `TeeInput` has 72 constructors (not a bad thing)!!

Anyway, seems to me like the solution would be to eliminate ctors that remove control of the output from the user.

So for example ctors like these would be removed:
```java
    public TeeInput(final CharSequence input, final File file) {
        this(new InputOf(input), new OutputTo(file));
    }

    public TeeInput(final Text text, final Path path) {
        this(new InputOf(text), new OutputTo(path));
    }
```

But ones like these would remain:
```java
    public TeeInput(final CharSequence input, final Output output) {
        this(new InputOf(input), output);
    }

    public TeeInput(final Input input, final Writer writer) {
        this(input, new OutputTo(writer));
    }
```

The key thing is that the user must remain in control of the `Output`. I think this would eliminate more than half of constructors. Users can compose an `Output` easily using `OutputTo`.

**Comment by Serranya** [comment] 2019-01-19 14:36
This constructor has the same problem:
```java
public TeeInput(final CharSequence input, final Output output) {
  this(new InputOf(input), output);
}

TeeInput will get an OutputStream from `Output` and will not close it. The caller now can't close it anymore. (Depending on the concrete `Output` class).

I think removing the "dangerous" constructors is one part of the solution. We should also improve documentation around this danger.

Not sure if there is something even better we can do.

**Comment by llorllale** [comment] 2019-01-23 01:21
@Serranya Imagine if both `Input` and `Output` were to extend `Closeable`.

Then we refactor `TeeInput` so that they cache the input and output streams (only a single stream is opened).

The question then would be, what would you call a `TeeInput` that also closes its `Output` when `TeeInput.close()` is called?

Would all this make sense/sound right?

**Comment by Serranya** [comment] 2019-01-23 08:48
> The question then would be, what would you call a TeeInput that also closes its Output when TeeInput.close() is called?

We could call it `ClosingTeeInput` or something like this. But I don't think I like the approach.

1. Instead of having composable behaviour we would just handcode a second TeeInput that also closes it's output
2. Right now it is possible (as far as I am aware) to read multiple times from the same `Input` but also to close the stream `cleanly` every time. This possibillity would be removed. We would have to know in advance if we are going to read from it another time. Right now we just close the stream and can get a new one if we need to.

**I think the best for now would be to just remove the "Dangerous" ctors and add maybe add some high level Javadoc  about which classes close there input how.**

**Comment by llorllale** [comment] 2019-01-24 14:26
@Serranya removing this ctor would be a showstopper:

```java
public TeeInput(final Input input, final Output output)
```

It's the reason for `TeeInput`'s existence in the first place.

I'm now thinking of reversing the change from #820 and adding warnings in the javadoc.

**Comment by Serranya** [comment] 2019-01-24 14:47
@llorllale That would also fix the risk of leaving the output open.

**Comment by svendiedrichsen** [comment] 2019-01-25 18:16
@llorllale How about a new decorator for TeeInput like i.e. ClosingTeeInput that closes the streams?

**Comment by Serranya** [comment] 2019-05-09 08:28
@llorllale ping

**Comment by llorllale** [comment] 2019-05-10 00:50
@Serranya fine, let's reverse #820 and add warnings to javadoc

**Comment by llorllale** [comment] 2019-05-10 00:50
@0crat in

**Comment by 0crat** [comment] 2019-05-10 00:53
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1024#issuecomment-491115696))

@llorllale Job [#1024](https://github.com/yegor256/cactoos/issues/1024) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2019-05-10 01:01
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @serranya[/z](https://www.0crat.com/u/serranya)

**Comment by 0crat** [comment] 2019-06-22 15:01
The job [#1024](https://github.com/yegor256/cactoos/issues/1024) assigned to @aivinog1[/z](https://www.0crat.com/u/aivinog1), here is [why](https://www.0crat.com/footprint/C63314D6Z/cae2c303-45a6-4eb9-839c-5662397248ea); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by aivinog1** [comment] 2019-06-25 12:03
@0crat wait #1148

**Comment by 0crat** [comment] 2019-06-25 12:05
> @0crat wait #1148 ([here](https://github.com/yegor256/cactoos/issues/1024#issuecomment-505414150))

@aivinog1 The impediment for [#1024](https://github.com/yegor256/cactoos/issues/1024) was registered successfully by @aivinog1[/z](https://www.0crat.com/u/aivinog1)

**Comment by aivinog1** [comment] 2019-06-26 02:43
@0crat continue

**Comment by 0crat** [comment] 2019-06-26 02:48
> @0crat continue ([here](https://github.com/yegor256/cactoos/issues/1024#issuecomment-505694999))

@aivinog1 @aivinog1[/z](https://www.0crat.com/u/aivinog1) continued working on job [#1024](https://github.com/yegor256/cactoos/issues/1024)

**Comment by aivinog1** [comment] 2019-06-27 05:52
@0crat wait #1149

**Comment by 0crat** [comment] 2019-06-27 05:52
> @0crat wait #1149 ([here](https://github.com/yegor256/cactoos/issues/1024#issuecomment-506201308))

@aivinog1 The impediment for [#1024](https://github.com/yegor256/cactoos/issues/1024) was registered successfully by @aivinog1[/z](https://www.0crat.com/u/aivinog1)

**Comment by 0crat** [comment] 2019-07-10 23:15
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @Serranya (its creator); I won't close the order; please, re-open it and ask @Serranya to close it

**Comment by aivinog1** [comment] 2019-07-11 00:34
@llorllale Can you reopen this issue that @Serranya can close this properly?

**Comment by 0crat** [comment] 2019-07-11 20:12
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-07-11 20:12
@serranya[/z](https://www.0crat.com/u/serranya) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by aivinog1** [comment] 2019-07-12 05:06
@0crat status

**Comment by 0crat** [comment] 2019-07-12 05:07
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1024#issuecomment-510746334))

@aivinog1 This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1024](https://github.com/yegor256/cactoos/issues/1024) is [in scope](http://www.zerocracy.com/policy.html#14) for 2mon
  * The role is `DEV`
  * The job is assigned to @aivinog1[/z](https://www.0crat.com/u/aivinog1) for [20days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @serranya[/z](https://www.0crat.com/u/serranya): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231024%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by aivinog1** [comment] 2019-07-12 05:11
@llorllale Hm, it seems to be that task is assigned to me, actually. How can we fix that?

**Closed** 2019-07-19 14:18 UTC
Labels: scope, waiting

**Comment by 0crat** [comment] 2019-07-19 14:38
Job `gh:yegor256/cactoos#1024` is not assigned, can't get performer

**Comment by 0crat** [comment] 2019-07-19 14:42
The job [#1024](https://github.com/yegor256/cactoos/issues/1024) is now out of scope
