### ISSUE TITLE
CheckedScalar

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#735] opened 2018-03-12 12:12 UTC
Let's create `CheckedScalar` which will throw exception specified by user.
```java
class CheckedScalar<T, E extends Exception> implements Scalar<T> {
     //...fields and ctors
    @Override
    public T value() throws E {
        //...
    }
}
```
For more details see [discussion](https://github.com/yegor256/cactoos/issues/656#issuecomment-370023982) in issue #656 
I can submit PR if you agree.

**Comment by 0crat** [comment] 2018-03-12 15:13
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment] 2018-03-13 12:37
@0crat assign @Vatavuk

**Comment by 0crat** [comment] 2018-03-13 12:54
> @0crat assign @Vatavuk  ([here](https://github.com/yegor256/cactoos/issues/735#issuecomment-372650640))

@yegor256 Thanks for your contribution, @vatavuk[/z](https://www.0crat.com/u/vatavuk)! If you would be a member of [the project](https://www.0crat.com/p/C63314D6Z), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment] 2018-03-13 12:54
> @0crat assign @Vatavuk  ([here](https://github.com/yegor256/cactoos/issues/735#issuecomment-372650640))

@yegor256 The job [#735](https://github.com/yegor256/cactoos/issues/735) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/C63314D6Z/721254004). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html). @vatavuk[/z](https://www.0crat.com/u/vatavuk) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains

**Comment by 0crat** [comment] 2018-03-13 12:55
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment] 2018-03-13 12:55
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment] 2018-03-18 12:56
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by Vatavuk** [comment] 2018-03-20 08:05
@yegor256 I would like to raise an impediment because the reviewer is not responding to my PR #738 .
I can't command 0crat since I'm not a member of the project. Could you help?

**Comment by 0crat** [comment] 2018-03-21 12:55
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment] 2018-03-21 14:15
@Vatavuk try to talk to Zerocrat, he should listen to you

**Comment by Vatavuk** [comment] 2018-03-21 15:58
@0crat waiting
Waiting for reviewer reaction.

**Comment by 0crat** [comment] 2018-03-21 15:58
You need to ask somebody to invite you: https://github.com/zerocracy/datum#invite-only

**Comment by yegor256** [comment] 2018-03-22 09:50
@Vatavuk fill this form, someone will help: https://www.0crat.com/join

**Comment by 0crat** [comment] 2018-03-22 15:48
> @0crat waiting Compensating time for absence of reviewer response. ([here](https://github.com/yegor256/cactoos/issues/735#issuecomment-375353128))

@Vatavuk The impediment for [#735](https://github.com/yegor256/cactoos/issues/735) was registered successfully by @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by Vatavuk** [comment] 2018-04-02 19:15
This PR is resolved in PR #738

**Comment by 0crat** [comment] 2018-04-02 19:31
@vatavuk[/z](https://www.0crat.com/u/vatavuk) the issue is closed not by @Vatavuk (its creator); I won't close the order; please, re-open it and ask @Vatavuk to close it

**Comment by Vatavuk** [comment] 2018-04-02 19:34
@yegor256 0crat won't close the order. How to deal with this?

**Comment by yegor256** [comment] 2018-04-02 20:35
@Vatavuk it was a bug; try to close again, please.

**Closed** 2018-04-02 20:44 UTC
Labels: scope

**Comment by 0crat** [comment] 2018-04-02 21:00
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2018-04-02 21:00
The job [#735](https://github.com/yegor256/cactoos/issues/735) is now out of scope

**Comment by Vatavuk** [comment] 2018-04-02 21:13
@elenavolokhova I confirm.

**Comment by elenavolokhova** [comment] 2018-04-02 21:13
@Vatavuk Thanks!

**Comment by elenavolokhova** [comment] 2018-04-02 21:13
@0crat quality acceptable

**Comment by 0crat** [comment] 2018-04-02 21:14
Order was finished, quality is "acceptable": +30 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment] 2018-04-02 21:14
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
